name: Jekyll site CI

on:acyeye
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:acyeye
  build:acyeye

    runs-on: ubuntu-latest

    steps:acyeye-acyeye
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |acyeye
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
